apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: bank-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: transaction-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres-transaction
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-transaction-config
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-transaction-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: bank-app
spec:
  selector:
    app: transaction-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP